import { FlatCompat } from '@eslint/eslintrc'
import js from '@eslint/js'
import prettierRecommended from 'eslint-plugin-prettier/recommended'

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
  recommendedConfig: js.configs.recommended,
})

const eslintConfig = [
  {
    ignores: [
      'node_modules/**',
      // Stale Yarn leftovers in an older checkout; `eslint --fix .` would
      // otherwise traverse and rewrite files inside them.
      '.yarn/**',
      '.next/**',
      '.contentlayer/**',
      'out/**',
      'build/**',
      'public/**',
      // Generated by Next and explicitly marked "should not be edited".
      'next-env.d.ts',
    ],
  },
  js.configs.recommended,
  // eslint-config-next has no flat-config export yet, so it is bridged
  // through FlatCompat. This also pulls in the react and react-hooks rules.
  ...compat.extends('next/core-web-vitals', 'plugin:@typescript-eslint/recommended'),
  // Must come last: disables stylistic rules that would fight Prettier.
  prettierRecommended,
  {
    rules: {
      'prettier/prettier': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // Node scripts run outside the bundler and use process/console freely.
    files: ['scripts/**/*.{js,mjs}', '*.config.{js,mjs}'],
    languageOptions: {
      globals: { process: 'readonly', console: 'readonly', __dirname: 'readonly' },
    },
  },
  {
    // CommonJS config files are loaded by Node, not bundled, so require() is
    // the correct form here.
    files: ['*.config.js', 'postcss.config.js', 'prettier.config.js'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
]

export default eslintConfig
