import js from '@eslint/js'
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import prettierRecommended from 'eslint-plugin-prettier/recommended'
import tseslint from 'typescript-eslint'

const eslintConfig = [
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      '.velite/**',
      'out/**',
      'build/**',
      'public/**',
      // Generated by Next and explicitly marked "should not be edited".
      'next-env.d.ts',
    ],
  },
  js.configs.recommended,
  // eslint-config-next 16 ships a native flat config, so it is imported
  // directly. Bridging it through @eslint/eslintrc's FlatCompat — which was
  // required up to v15 — now throws on a circular `react` reference.
  ...nextCoreWebVitals,
  ...tseslint.configs.recommended,
  // Must come last: disables stylistic rules that would fight Prettier.
  prettierRecommended,
  {
    rules: {
      'prettier/prettier': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // Node scripts run outside the bundler and use process/console freely.
    files: ['scripts/**/*.{js,mjs}', '*.config.{js,mjs}'],
    languageOptions: {
      globals: { process: 'readonly', console: 'readonly', __dirname: 'readonly' },
    },
  },
  {
    // MDXContent builds its component from a compiled-MDX string, which cannot
    // be hoisted to module scope — that is the component's entire purpose. The
    // rule guards against remounting a fresh identity each render; the module
    // level cache keeps identity stable, and it is a server component rendered
    // once at build time. Expressed here rather than as an inline directive
    // because prettier reflows the surrounding comment and eslint --fix then
    // removes the directive as unused.
    files: ['components/MDXContent.tsx'],
    rules: { 'react-hooks/static-components': 'off' },
  },
  {
    // CommonJS config files are loaded by Node, not bundled, so require() is
    // the correct form here.
    files: ['*.config.js', 'postcss.config.js', 'prettier.config.js'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
]

export default eslintConfig
